### PR TITLE
Added Customer model

### PR DESCRIPTION
**Pull request by agrzelewska**
Customer model with validation (name, email) added

### CODE REVIEW

**Comment by gpks** [comment]
Have you created it with a scaffold?

**Comment by agrzelewska** [comment]
Yes, I did it with a scaffold

**Comment by gpks** [comment]
Could I ask why?
Don't get me wrong, scaffolds are giving quick results, but they also create a lot for you, so you have code that is done for you, without getting into details. 
Do you know what file `test/controllers/customers_controller_test.rb` does? What is going on in every controller method? Would you be able to obtain the same result without using scaffold?

**Comment by gpks** [comment]
I think `rails generate model ...` method is enough for this task...

**Comment by agrzelewska** [comment]
I guess that after a few days of a few hour each day spent of instalations I've chosen just the first method on my mind :). I've done some tutorial projects without scaffold so I know more over what controller method are for. But I can make the second Customer branch from the scratch, generating model, controller etc. Hope I'll manage it tonight :)

**Comment by agrzelewska** [comment]
ok :). Just model :)

**Comment by gpks** [comment]
I know that setting up an environment is a pain in the ass, and it's awful, takes a lot of time and can be really frustrating. But it's the one thing in the developers' toolbox that we just need to know, or at least know how to google it ;). When I started out new job couple of months ago it took me 3 days of 8 hours work to set up an environment (3 main apps, one in ancient ruby and ancient rails). So please don't get discouraged by this kind of problems, it's a part of being a developer!

**Comment by gpks** [comment]
And getting back to this task: we don't need index or show on a customer, it will be handled as signup etc. So scaffold is obsolete in this task and can be misleading for others...

**Comment by agrzelewska** [comment]
Whatever doesn't kill us can make us stronger :)

**Pull request closed without merging**
